// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKOwxpZyRIKkHbC0xKnZHKasC2uWhEKDc',
    appId: '1:941632848340:web:93c182801e5171152fd641',
    messagingSenderId: '941632848340',
    projectId: 'iitj-menu-89112',
    authDomain: 'iitj-menu-89112.firebaseapp.com',
    storageBucket: 'iitj-menu-89112.firebasestorage.app',
    measurementId: 'G-JSF2VYTB4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVMMNYSaMTNPQFl5kIS4c9J-6YlH0RilM',
    appId: '1:941632848340:android:6c0d4639f8c55f112fd641',
    messagingSenderId: '941632848340',
    projectId: 'iitj-menu-89112',
    storageBucket: 'iitj-menu-89112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndAhpyOv26Q-4RDae19SmlAPxcmxiQyk',
    appId: '1:941632848340:ios:0ebc691c584452292fd641',
    messagingSenderId: '941632848340',
    projectId: 'iitj-menu-89112',
    storageBucket: 'iitj-menu-89112.firebasestorage.app',
    iosBundleId: 'com.appier.iitjmenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDndAhpyOv26Q-4RDae19SmlAPxcmxiQyk',
    appId: '1:941632848340:ios:0ebc691c584452292fd641',
    messagingSenderId: '941632848340',
    projectId: 'iitj-menu-89112',
    storageBucket: 'iitj-menu-89112.firebasestorage.app',
    iosBundleId: 'com.appier.iitjmenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKOwxpZyRIKkHbC0xKnZHKasC2uWhEKDc',
    appId: '1:941632848340:web:9f1443474fcdeb7f2fd641',
    messagingSenderId: '941632848340',
    projectId: 'iitj-menu-89112',
    authDomain: 'iitj-menu-89112.firebaseapp.com',
    storageBucket: 'iitj-menu-89112.firebasestorage.app',
    measurementId: 'G-NQ9HHGVJLP',
  );

}